services:
  broker:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Management UI
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
